name: musicify
description: "Music Player App."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  assets_audio_player: ^3.0.5
  cupertino_icons: ^1.0.2
  file_picker: ^8.0.6
  flutter:
    sdk: flutter
  on_audio_query: ^2.9.0
  palette_generator: ^0.3.3+2
  permission_handler: ^11.3.1
  sleek_circular_slider: ^2.0.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
  # fonts:
  #   - family: Circular Std
  #     fonts:
  #       - asset: assets/fonts/CircularStd-Book.otf
  #       - asset: assets/fonts/CircularStd-Medium.otf
  #         weight: 600
  #       - asset: assets/fonts/CircularStd-Bold.otf
  #         weight: 700
  #       - asset: assets/fonts/CircularStd-Black.otf
  #         weight: 800
